[paths]
baseDir = "./"
dataDir = "./data"

[pg]
database = "db4s_stats"
num_connections = 45
password = "yourpassword"
port = 5432
server = "127.0.0.1"
ssl = true
username = "youruser"

[server]
debug = false
port = 9080
sslport = 9443

[tls]
certfile = ""
keyfile = ""
